FROM python:3.11

COPY webapp /opt/webapp
COPY intersystems_irispython-3.2.0-py3-none-any.whl /opt/intersystems_irispython-3.2.0-py3-none-any.whl
RUN pip install flask /opt/intersystems_irispython-3.2.0-py3-none-any.whl

CMD ["python", "/opt/webapp/flask_app.py"]