version: '1.0'
services:
  iris:
    image: uki-python-dev
    build:
      context: ./
      dockerfile : Dockerfile
      args:
        - IRIS_PASSWORD=${IRIS_PASSWORD:-SYS}
    command: --check-caps false
    volumes:
      - ./:/irisdev/app/
    environment:
      - ISC_CPF_MERGE_FILE=/irisdev/app/merge.cpf
    ports:
    - 52781:52773
    - 8100:8080
