version: '2.0'
services:
  iris:
    image: uki-python-iris
    build:
      context: ./
      dockerfile : Dockerfile.IRIS
      args:
        - IRIS_PASSWORD=${IRIS_PASSWORD:-SYS}
    command: --check-caps false
    volumes:
      - ./:/irisdev/app/
    ports:
    - 52781:52773
    - 51781:1972
    networks:
      - iris-flask
    healthcheck:
      test: /irisHealth.sh
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 8s

  flask:
    image: uki-python-flask
    environment:
      IRIS_USERNAME: SuperUser
      IRIS_PASSWORD: SYS
      IRIS_HOST: iris
      IRIS_PORT: 1972
      IRIS_NAMESPACE: UKI-PYTHON-DEV
    build:
      context: ./
      dockerfile: Dockerfile.Flask
    depends_on:
      iris:
        condition: service_healthy
    ports: 
    - 8080:8080
    networks:
      - iris-flask
  
networks:
  iris-flask:
    
